blog_app/config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog_app/app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { minimum: 1, maximum: 140 }
end

blog_app/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy] # destroyアクションを追加

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

blog_app/app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm" || action_name == "create"
      confirm_blogs_path
    elsif action_name == "edit"
      blog_path
    end
  end
end

blog_app/app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true,url: choose_new_or_edit) do |form| %>

<% if @blog.errors.any? %>
<div id="error_explanation">
  <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
  <ul>

    <% @blog.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="blog_title">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>
<div class="blog_title">
  <%= form.label :content %>
  <%= form.text_field :content %>
</div>
<%= form.submit  "登録する" %>

<%= form.submit "戻る", name: 'back' %>
<% end %>

blog_app/app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, local: true ) do |form| %>
<%= form.hidden_field :title %>
<%= form.hidden_field :content %>

<p>タイトル:<%= @blog.title %></p>
<p>本文:<%= @blog.content %></p>
<%= form.submit  "登録する" %>
<% end %>

blog_app/app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>
<p>Find me in app/views/blogs/edit.html.erb</p>
<h2>ブログを編集する</h2>
<%= render 'form' %>

blog_app/app/views/blogs/index.html.erb
<div class="container">
  <div class="container">
    <header class="header col-md-6">Bootstrap</header>
    <button type="button" class="label label-success btn btn-default">Challenge!</button>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bootstrap</a>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="">top</a></li>
          <li><a href="">menu1</a></li>
          <li><a href="">menu2</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <article>
    <div class="contents">
      <ul>
        <li class="col-md-6">contents1</li>
        <li class="col-md-6">contents2</li>
        <li class="col-md-6">contents3</li>
        <li class="col-md-6">contents4</li>
      </ul>
    </div>
    <div class="topic">
      <ul>
        <li>bootstrapを使ってレスポンシブデザインを実現しよう！</li>
        <li>やればできる！bootstrapを使ってみよう！</li>
        <li>怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に！</li>
      </ul>
    </div>
  </article>
</div

blog_app/app/views/blogs/new.html.erb
<h1>Blogs#new</h1>
<p>Find me in app/views/blogs/new.html.erb</p>

<h2>ブログを作成する</h2>
<%= render 'form' %>

blog_app/app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<p>Find me in app/views/blogs/show.html.erb</p>
<p>タイトル: <%= @blog.title %> </p>
<p>内容: <%= @blog.content %> </p>


<%= link_to 'ブログを編集する', edit_blog_path(@blog.id) %>

blog_app/app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

blog_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BlogApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width"> <!-- head内にこのタグ設定を追記する -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>


<footer>
  <p>運営会社DIVE INTO CODE株式会社</p>
  <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
</footer>

</html>